### ISSUE TITLE
nested tag issue, beyond scope of library?

### ISSUE THREAD

**Issue by svenevs** [martinblech/xmltodict#160] opened 2017-07-19 08:58 UTC
I'm having a hard time understanding why the output I am getting is formatted the way it is.

## Admonition

I think this may be "beyond" the scope of capabilities of this library.  I don't know much about the formal `xml` standards, but I suspect that the tags parsed correctly such as `para` or `orderedlist` are standardized where as the breaking ones (e.g. `computeroutput`) are not?

I don't think the application purpose is relevant, but I'm playing around with the doxygen xml output.  These tags are defined in a `compound.xsd` document I can include if desired, but some correctly parsed (`orderedlist`) tags are defined in this -- AKA I'm not sure if this is a bug or unsupported feature.

## Breaking input

```py
#!/usr/bin/env python3
import textwrap
import xmltodict
import json

raw_xml = textwrap.dedent('''
<detaileddescription>
    <para>
        There <computeroutput>once</computeroutput> was a lad who wanted to accomplish things.
    </para>
    <para>
        <orderedlist>
            <listitem><para>He did stuff. There was nothing else he could do.</para></listitem>
            <listitem><para>He enumerated stuff.</para></listitem>
            <listitem><para>He listed stuff. </para></listitem>
        </orderedlist>
    </para>
</detaileddescription>
''')

xml_dict = xmltodict.parse(raw_xml)
print(json.dumps(xml_dict, indent=4))

print("*" * 77)

print(xmltodict.unparse(xml_dict, pretty=True))
```

### Output json

```json
{
    "detaileddescription": {
        "para": [
            {
                "computeroutput": "once",
                "#text": "There  was a lad who wanted to accomplish things."
            },
            {
                "orderedlist": {
                    "listitem": [
                        {
                            "para": "He did stuff. There was nothing else he could do."
                        },
                        {
                            "para": "He enumerated stuff."
                        },
                        {
                            "para": "He listed stuff."
                        }
                    ]
                }
            }
        ]
    }
}
```

### Output xml

```xml
<?xml version="1.0" encoding="utf-8"?>
<detaileddescription>
	<para>
		<computeroutput>once</computeroutput>
There  was a lad who wanted to accomplish things.	</para>
	<para>
		<orderedlist>
			<listitem>
				<para>He did stuff. There was nothing else he could do.</para>
			</listitem>
			<listitem>
				<para>He enumerated stuff.</para>
			</listitem>
			<listitem>
				<para>He listed stuff.</para>
			</listitem>
		</orderedlist>
	</para>
</detaileddescription>
```

What leads the `computeroutput` tag to behave this way?  If you think it's easy to patch I'm down to take a look with some guidance, I **love** being able to parse xml dictionary style :smile:

**Comment by martinblech** [comment] 2017-07-19 19:06
This is a duplicate of #63

**Closed** 2017-07-19 19:06 UTC
Labels: duplicate

**Comment by javadev** [comment] 2018-12-03 13:22
```xml
<detaileddescription>
    <para>
        There <computeroutput>once</computeroutput> was a lad who wanted to accomplish things.
    </para>
    <para>
        <orderedlist>
            <listitem><para>He did stuff. There was nothing else he could do.</para></listitem>
            <listitem><para>He enumerated stuff.</para></listitem>
            <listitem><para>He listed stuff. </para></listitem>
        </orderedlist>
    </para>
</detaileddescription>
```
may be converted to json:
```json
{
  "detaileddescription": {
    "para": [
      {
        "#text": "\n        There ",
        "computeroutput": "once",
        "#text1": " was a lad who wanted to accomplish things.\n    "
      },
      {
        "orderedlist": {
          "listitem": [
            {
              "para": "He did stuff. There was nothing else he could do."
            },
            {
              "para": "He enumerated stuff."
            },
            {
              "para": "He listed stuff. "
            }
          ]
        }
      }
    ]
  },
  "#omit-xml-declaration": "yes"
}
```
and back to the xml:
```xml
<detaileddescription>
  <para>
        There <computeroutput>once</computeroutput> was a lad who wanted to accomplish things.
    </para>
  <para>
    <orderedlist>
      <listitem>
        <para>He did stuff. There was nothing else he could do.</para>
      </listitem>
      <listitem>
        <para>He enumerated stuff.</para>
      </listitem>
      <listitem>
        <para>He listed stuff. </para>
      </listitem>
    </orderedlist>
  </para>
</detaileddescription>
```
