### ISSUE TITLE
no element found: line 1, column 0

### ISSUE THREAD

**Issue by HAMZARaouia** [martinblech/xmltodict#217] opened 2019-05-29 10:35 UTC
parser.Parse(xml_input, True) xml.parsers.expat.ExpatError: no element found: line 1, column 0

my python version is 3.7

is this error has to do with this version ?

**Comment by jschukat** [comment] 2019-06-03 15:32
I had the same error. In my case it was due to me calling `doc = xmltodict.parse('file.xml')`

I was able to get rid of the error by calling:
`with open('file.xml') as fd:
    doc = xmltodict.parse(fd.read())`
instead.

**Comment by tngan** [comment] 2019-07-24 08:31
@HAMZARaouia Check if there is missing closing tags.

**Comment by domsooch** [comment] 2019-10-03 00:56
I'm getting this error with this input:
s=
<node id="47919963" version="3" timestamp="2015-08-04T04:17:42Z" uid="0" user="" lat="46.235324" lon="-119.064277">
    <tag k="highway" v="turning_circle"/>
    <node id="47920230" version="3" timestamp="2014-01-08T15:16:16Z" uid="0" user="" lat="46.297798" lon="-119.248404">
    <tag k="highway" v="turning_circle"/>
   </node>

S=r"""%s"""%(s.strip())
xmltodict.parse(S)

--> 327         parser.Parse(xml_input, True)
    328     return handler.item
    329 

ExpatError: no element found: line 5, column 10

**Comment by tank2737** [comment] 2020-01-21 06:05
unable to parse <?xml version="1.0" ?>

**Comment by tank2737** [comment] 2020-01-21 06:05
‘’<?xml version="1.0" ?>“”

**Comment by hartwork** [comment] 2022-05-08 11:08
The XML presented is malformed. My vote for closing as "not a bug in xmltodict".

**Closed** 2022-05-08 15:57 UTC
Labels: invalid
