### ISSUE TITLE
bash: line 1:  1374 Killed

### ISSUE THREAD

**Issue by lerchikva** [martinblech/xmltodict#259] opened 2020-09-21 13:15 UTC
Hello.
Please help XML to JSON.
I am low on RAM so the server is killing the process.

`python -c 'import xmltodict, sys, json; json.dump(xmltodict.parse(sys.stdin.read(), process_namespaces=True), sys.stdout, indent=4);' < ./public/my.xml > ./public/my.json`

```
bash: line 1:  1374 Killed                  python -c 'import xmltodict, sys, json; json.dump(xmltodict.parse(sys.stdin.read(), process_namespaces=True), sys.stdout, indent=4);' < ./public/my.xml > ./public/my.json
```

**Comment by okyanusoz** [comment] 2020-12-27 14:43
Hello,
It seems like you're working with a large file. Consider using [Streaming Mode](https://github.com/martinblech/xmltodict#streaming-mode).

**Comment by hartwork** [comment] 2022-05-08 11:04
My vote for closing as "not a bug in xmltodict".

**Closed** 2022-05-08 16:22 UTC
